version: 2.1
orbs:
  node: circleci/node@4.7
  docker: circleci/docker@2.2.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: xindunglangim/react
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b5:9a:39:bc:ad:6c:87:68:f4:51:01:38:9e:88:31:55"
      - run: ssh -oStrictHostKeyChecking=no root@13.215.157.85 './deploy.sh'

workflows:
  build-push-deploy:
    jobs:
      - node/test
      - build-and-push:
          requires:
            - node/test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build-and-push
