version: 2.1
orbs:
  node: circleci/node@4.7
  docker: circleci/docker@2.2.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: xindunglangim/react
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      - add_ssh_keys:
          fingerprints:
            - "90:66:4b:18:42:0b:c7:12:69:9a:55:0b:6c:e8:4b:bb"
      - run: ssh -o StrictHostKeyChecking=no root@ip-172-31-10-227.ap-southeast-1.compute.internal './deploy.sh'

workflows:
  build-push-deploy:
    jobs:
      - node/test
      - build-and-push:
          requires:
            - node/test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build-and-push
